#!/bin/sh
# preinst script for auditd

set -e

case "$1" in
    upgrade)
	# This used to be a conffile, but we don't want it to be any
	# more as it's always generated at daemon startup
	# now. Removing it in preinst will fix things up in dpkg's
	# conffile tracking.
	rm -f /etc/audit/audit.rules
    ;;

    install|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
