.TH "AUDISPD" "8" "Jun 2008" "Debian" "System Administration Utilities"
.SH NAME
system\-config\-audit \- Graphical utility for editing audit configuration

.SH SYNOPSIS
.B system\-config\-audit

.SH DESCRIPTION
\fBsystem\-config\-audit\fP is a graphical userspace utility for the Linux Auditing System. It can be used to edit the configuration files.

.SH "SEE ALSO"
.BR auditd (8).

.SH AUTHOR
system\-config\-audit was written by Miloslav Trmac <mitr@redhat.com>.
.PP
This manual page was written by Philipp Hahn <pmhahn@debian.org>,
for the Debian project (but may be used by others).
